# **Linear Algebra** 🔢

Vectors and matrices are fundamental building blocks of data science as they are used to organize and manipulate data we feed through learning models. Linear algebra focuses on the mathematics surrounding linear operations and solving systems of linear equations. While most of us learned about basic linear operations in algebra classes in high school and middle school, “linear algebra” extends these lessons to apply to multi-dimensional data.

Linear algebra focuses on the mathematics surrounding linear operations and solving systems of linear equations. While most of us learned about basic linear operations in algebra classes in high school and middle school, “linear algebra” extends these lessons to apply to multi-dimensional data.

The core of using NumPy effectively for linear algebra is using NumPy arrays. NumPy arrays are n-dimensional array data structures that can be used to represent both vectors (1-dimensional array) and matrices (2-dimensional arrays).

A NumPy array is initialized using the `np.array()` function, and including a Python list 
argument or Python nested list argument for arrays with more than one dimension.

In [ ]:
import numpy as np

## **Vectors**

The fundamental building blocks of linear algebra are vectors. Vectors are defined as quantities having both direction and magnitude, compared to scalar quantities that only have magnitude. In order to have direction and magnitude, vector quantities consist of two or more elements of data. The dimensionality of a vector is determined by the number of numerical elements in that vector.

Any vector can be multiplied by a scalar, which results in every element of that vector being multiplied by that scalar individually. Vectors can be added and subtracted from each other when they are of the same dimension (same number of components).

In [ ]:
v = np.array([1, 2, 3, 4, 5, 6])
v

array([1, 2, 3, 4, 5, 6])

### **Magnitude**

The magnitude (or length) of a vector, $||v||$, can be calculated with the following formula:

$||v||=\sqrt{\sum_{i=1}^nv_i^2}$

The “norm” (or length/magnitude) of a vector can be found using `np.linalg.norm()`:

In [ ]:
v = np.array([-2, -3, 0, 5, 1])
v_norm = np.linalg.norm(v)
print(v_norm)

6.244997998398398


### **Dot Product**

An important vector operation in linear algebra is the dot product. A dot product takes two equal dimension vectors and returns a single scalar value by summing the products of the vectors’ corresponding components. This can be written out formulaically as:

$a\cdot b = \sum_{i=1}^na_ib_i$

The resulting scalar value represents how much one vector “goes into” the other vector. If two vectors are perpendicular (or orthogonal), their dot product is equal to 0, as neither vector “goes into the other.”

To find the magnitude of a vector it is simply the square root of a vector’s dot product with itself.

$||a|| = \sqrt{a\cdot a}$

To find the angle between two vectors, we rely on the dot product between the two vectors and use the following equation.

$\theta=\arccos\Large\frac{a\cdot b}{||a|| ||b||}$

Vector dot products can be computed using the `np.dot()` function:

In [ ]:
v = np.array([-1, -2, -3])
u = np.array([2, 2, 2])
print(np.dot(v, u))

-12


In [ ]:
v = np.array([3, -1, 2])
u = np.array([0, -1, 1])
theta = np.arccos(np.dot(v, u) / (np.linalg.norm(v) * np.linalg.norm(u)))
degree_theta = np.degrees(theta)
print(degree_theta)

55.46241621381916


## **Matrices**

A matrix is a quantity with m rows and n columns of data. For example, we can combine multiple vectors into a matrix where each column of that matrix is one of the vectors. Matrices are helpful because they allow us to perform operations on large amounts of data, such as representing entire systems of equations in a single matrix quantity. The shape of a matrix is said to be mxn, where there are m rows and n columns. 

We can again both multiply entire matrices by a scalar value, as well as add or subtract matrices with equal shapes.

In [ ]:
A = np.array([[1, 2], [3, 4]])
print(A)

[[1 2]
 [3 4]]


Matrices can also be created by combining existing vectors using the `np.column_stack()` function:

In [ ]:
v = np.array([-2, -2, -2, -2])
u = np.array([0, 0, 0, 0])
w = np.array([3, 3, 3, 3])

A = np.column_stack((v, u, w))
print(A)

[[-2  0  3]
 [-2  0  3]
 [-2  0  3]
 [-2  0  3]]


To access the shape of a matrix or vector once it’s been created as a NumPy array, we call the `.shape` attribute of the array variable:

In [ ]:
A = np.array([[1, 2], [3, 4]])
print(A.shape)

(2, 2)


To access individual elements in a NumPy array, we can index the array using square brackets. Unlike regular Python lists, we can index into all dimensions in a single square bracket, separating the dimension indices with commas.

In [ ]:
A = np.array([[1, 2], [3, 4]])
print(A[0, 1])

2


We can also select a subset or entire dimension of a NumPy array using a colon. For example, if we want the entire second column of a matrix, we can index the second column and use an empty colon to select every row as such:

In [ ]:
A = np.array([[1, 2], [3, 4]])
print(A[:, 1])

[2 4]


To multiply a vector or matrix by a scalar, we use inbuilt Python multiplication between the NumPy array and the scalar:

In [ ]:
A = np.array([[1, 2], [3, 4]])
4 * A

array([[ 4,  8],
       [12, 16]])

To add equally sized vectors or matrices, we can again use inbuilt Python addition between the NumPy arrays.

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[-4, -3], [-2, -1]])
A + B

array([[-3, -1],
       [ 1,  3]])

### **Matrix Multiplication**

A new and important operation we can now perform is matrix multiplication. Matrix multiplication works by computing the dot product between each row of the first matrix and each column of the second matrix.

An important rule about matrix multiplication is that the shapes of the two matrices AB must be such that the number of columns in A is equal to the number of rows in B. 

![image.png](attachment:image.png)

Matrix multiplication is computed using either the `np.matmul()` function or using the `@` symbol as shorthand. It is important to note that using the typical Python multiplication symbol `*` will result in an elementwise multiplication instead.

In [ ]:
A = np.array([[2, -3, 1], [-2, -1, 4], [0, 2, 2]])
B = np.array([[3, -2, 1], [1, -1, 2], [-2, 2, 0]])

# one way to matrix multiply
np.matmul(A, B)

array([[  1,   1,  -4],
       [-15,  13,  -4],
       [ -2,   2,   4]])

In [ ]:
# another way to matrix multiply
A @ B

array([[ -8,  -5],
       [-20, -13]])

### **Special Matrices**

#### **Identity Matrix**

The identity matrix is a square matrix of elements equal to 0 except for the elements along the diagonal that are equal to 1. Any matrix multiplied by the identity matrix, either on the left or right side, will be equal to itself.

$
\begin{bmatrix}
1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & 1
\end{bmatrix}
$


An identity matrix can be constructed using the `np.eye()` functions, which takes an integer argument that determines the $n x n$ size of the square identity matrix.

In [ ]:
# 4x4 identity matrix
identity = np.eye(4)
identity

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

A matrix or vector of all zeros can be constructed using the `np.zeros()` function, which takes in a tuple argument for the shape of the NumPy array filled with zeros.

In [ ]:
# 3x2 matrix of zeros
zero_matrix = np.zeros((3, 2))
zero_matrix

array([[0., 0.],
       [0., 0.],
       [0., 0.]])


#### **Permutation Matrix**

A permutation matrix is a square matrix that allows us to flip rows and columns of a separate matrix. Similar to the identity matrix, a permutation matrix is made of elements equal to 0, except for one element in each row or column that is equal to 1. In order to flip rows in matrix A, we multiply a permutation matrix P on the left (PA). To flip columns, we multiply a permutation matrix P on the right (AP).

$ P =
\begin{bmatrix}
0 & 0 & 1\\
0 & 0 & 1\\
1 & 0 & 0
\end{bmatrix}
$



#### **Transpose Matrix**

The transpose of a matrix is computed by swapping the rows and columns of a matrix. The transpose operation is denoted by a superscript uppercase “T” ($A^T$).

The transpose of a matrix can be accessed using the `.T` attribute of a NumPy array as shown below:

In [ ]:
A = np.array([[1, 2], [3, 4]])
A_transpose = A.T
A_transpose

array([[1, 3],
       [2, 4]])

## **Linear Systems**

An extremely useful application of matrices is for solving systems of linear equations.

$a_1x+b_1y+c_1z=d_1$

$a_2x+b_2y+c_2z=d_2$

$a_3x+b_3y+c_3z=d_3$

This system of equations can be represented using vectors and their linear combination operations.

![image.png](attachment:image.png)

Our final goal is going to be to represent this system in form $Ax = b$.

![image-2.png](attachment:image-2.png)

This is what is known as an augmented matrix.

### **Gauss-Jordan Elimination**

Now that we have our system of linear equations in augmented matrix form, we can solve for the unknown variables using a technique called Gauss-Jordan Elimination. In regular algebra, we may try to solve the system by combining equations to eliminate variables until we can solve for a single one. Having one variable solved for then allows us to solve for a second variable, and we can continue that process until all variables are solved for.

To solve for the system, we want to put our augmented matrix into something called row echelon form where all elements below the diagonal are equal to zero.

![image.png](attachment:image.png)

Note that the values with apostrophes in the row echelon form matrix mean that they have been changed in the process of updating the matrix. Once in this form we can rewrite our original equation as:

![image.png](attachment:image.png)

To get to row echelon form we swap rows and/or add or subtract rows against other rows. A typical strategy is to add or subtract row 1 against all rows below in order to make all elements in column 1 equal to 0 under the diagonal. Once this is achieved, we can do the same with row 2 and all rows below to make all elements below the diagonal in column 2 equal to 0.

Once all elements below the diagonal are equal to 0, we can simply solve for the variable values, starting at the bottom of the matrix and working our way up.

It’s important to realize that not all systems of equations are solvable!

Finally, we can actually solve for unknown variables in a system on linear equations in $Ax=b$ form using `np.linalg.solve()`, which takes in the $A$ and $b$ parameters.

In [ ]:
# each array in A is an equation from the above system of equations
A = np.array([[2, -3, 1], [3, 1, 1], [-1, -2, -1]])
# the solution to each equation
b = np.array([2, -1, 1])
# solve for x, y, and z
x, y, z = np.linalg.solve(A, b)
print((x, y, z))

(np.float64(-0.3333333333333335), np.float64(-0.6666666666666666), np.float64(0.6666666666666669))


### **Inverse Matrics**

The inverse of a matrix, $A^{-1}$, is one where the following equation is true:

$AA^{−1}=A^{−1}A=I$

This means that the product of a matrix and its inverse (in either order) is equal to the identity matrix. An important consideration to keep in mind is that not all matrices have inverses. Those matrices that do not have an inverse are referred to as singular matrices.

To find the inverse matrix, we can again use Gauss-Jordan elimination. Knowing that $AA^{-1} = I$, we can create the augmented matrix $[ A | I ]$, where we attempt to perform row operations such that $[ A | I ] \rightarrow [ I | A^{-1} ]$.

The inverse of a square matrix, if one exists, can be found using `np.linalg.inv()`:

In [ ]:
A = np.array([[1, 2], [3, 4]])
print(np.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


# **Extra Reading**

https://medium.com/@amehsunday178/a-deep-dive-into-vector-spaces-the-core-meaning-of-eigenvalues-eigenvectors-eigendecomposition-c496b8926554